### ISSUE TITLE
Add a `CHANGELOG` for each releases

### ISSUE THREAD

**Issue by ManevilleF** [nmandery/h3ron#14]
It would be nice to have a list of changes (especially breaking ones) available.

Also Github provides the *release*  system that can use this file.

If you also add a  `CONTRIBUTING`, contributors could write their PR changes under a `Unreleased`  section

**Comment by nmandery** [comment]
I definitely agree. I will add changelog based on https://keepachangelog.com/en/1.0.0/ .

**Comment by ManevilleF** [comment]
Great ! Not many people use this library but we added quite a lot of breaking changes recently and it would be good to have a changelog when the `0.10.0` is released
