### ISSUE TITLE
Add wrappers for missing `h3ron-sys` bindings

### ISSUE THREAD

**Issue by ManevilleF** [nmandery/h3ron#3]
A few methods are not available in the `h3ron` crate but are available in the C bindings `h3ron-sys`.

- `h3Line`
- `h3LineSize`
- `getBaseCell`
etc

I can try to make a PR with the implementation if this is too much work

**Comment by nmandery** [comment]
I implemented the wrappers for the line-functions a few days ago (in 282e474959f94c1f2d45c7e92385a67e0a4528fd), `getBaseCell` is in b5438af44a97acd997e1d57d6c67446488e08fbb.

I just did not do an release yet. Just have a look in the master branch if you are missing anything. PRs are of course welcome ;)

**Comment by ManevilleF** [comment]
Thank you !
