### ISSUE TITLE
A faster h3IsValid

### ISSUE THREAD

**Issue by slaperche-zenly** [nmandery/h3ron#34]
First and foremost: thanks for this great crate 🙏 
Been using for a few days, and the high level API is really enjoyable 👍 

I've been working with H3 these last few months, and one thing leading to another I've found that the current implementation of `h3IsValid` seems suboptimal (contains for-loops that could be avoided).
Given that I have to validate set of cells that can be quite large in some case, I gave it a shot at optimizing it.

After a few attempts, I arrrived to a solution that seems to be isofunctional while being x3 to x4 faster than the original implementation:
- [Criterion output for hexagons](https://user-images.githubusercontent.com/77592810/153739406-f861c283-584d-4277-ae16-257a23541222.png)
- [Criterion output for pentagons](https://user-images.githubusercontent.com/77592810/153739409-ce9b266d-ed18-4806-99f3-be74d654a7bc.png)

Code is not necessarily more complex (I would even say it's simpler but I'm not objective here 😀), though there are one or two tricks that do deserve detailed explanations.

The two biggests improvements are:
- replacing the loop checking for invalid digits using an adaptation of an old nul-byte detection algorithm (_technology from the past come to save the future_ 😛)
- replacing the loop checking for invalid pentagons

You can find the code [here](https://gist.github.com/slaperche-zenly/204e9b8e305cfb8ce2eec49fbe7b9396) (with some unit tests).
The benchmarks I used is [here](https://gist.github.com/slaperche-zenly/32e6e19db4c1a0eda1a19c54a90e7669).

I've also run [a check again a few billions of value](https://gist.github.com/slaperche-zenly/2b28b2139de2b27f68a1780c71bf694a) (~30% valid/70% invalid) with my implementation against the official ones to ensure that the results were identical.
Interestingly enough, I can observe the same x3 speedup [in this case](https://gist.github.com/slaperche-zenly/21f59b36dc954b20295193ed8bba464d) (on my machine ~8s vs ~24s)

Dunno if it's of interest to you, but I'm sharing it just in case 🙂

Would probably be better to implement this upstream, but I don't have the time nor the motivation to start a pull request in C 😅 (that being said, they do have [a PR in progress](https://github.com/uber/h3/pull/496) about this, and I did [left a comment](https://github.com/uber/h3/pull/496/files#r795851046) over there as well 🙂).

**Comment by nmandery** [comment]
I am glad when this library is helpful to you :+1: 

Great work on the optimization of `h3IsValid`  - the speedup achieved by this is really remarkable. This is definitely very interesting, thank you for sharing.

I saw that there is already some work done to look how to integrate this into h3 itself. This would certainly the best way to integrate this patch. I would propose to see how that works out. In case there are issues with porting this code to portable C while supporting all platforms H3 compiles to, we really should integrate your code into `h3ron`.

**Comment by slaperche-zenly** [comment]
> I would propose to see how that works out. In case there are issues with porting this code to portable C while supporting all platforms H3 compiles to, we really should integrate your code into h3ron.

Sounds good to me, let's wait and see 🙂

**Comment by nmandery** [comment]
I suppose we can close this issue as this is certainly implemented now in [h3o](https://github.com/HydroniumLabs/h3o)
