### ISSUE TITLE
Feature indexmap is not defined in Cargo.toml

### ISSUE THREAD

**Issue by thehardbits** [nmandery/h3ron#65]
To enable h3ron::algorithm::cell_clusters module **indexmap** feature have to be enabled, as defined  [here](https://docs.rs/h3ron/latest/h3ron/algorithm/cell_clusters/fn.find_cell_clusters.html). But there is no such feature in [h3ron Cargo.toml](https://github.com/nmandery/h3ron/blob/main/h3ron/Cargo.toml).

**Comment by nmandery** [comment]
There is no explicit feature defined, yes, but the `indexmap` dependeny is optional:

https://github.com/nmandery/h3ron/blob/7d7383baa86abf0ff69d9b962c680e7f45b54f32/h3ron/Cargo.toml#L26

This [works the same way as a feature](https://doc.rust-lang.org/cargo/reference/features.html), but maybe is less visible. I will add this as an feature, but it should work like it is right now.
