### ISSUE TITLE
Improve github actions workflows

### ISSUE THREAD

**Issue by nmandery** [nmandery/h3ron#7]
* test on multiple platforms
* build and publish releases for multiple platforms

The [workflows of pyca/cryptography](https://github.com/pyca/cryptography/tree/main/.github/workflows) can be used as an example  as most of the dependencies are the same.

Windows images already include cmake - see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by nmandery** [comment]
Also see https://github.com/konstin/complex-manylinux-maturin-docker on how to build with maturin for pypi

**Comment by nmandery** [comment]
hyperjson has a nice simple [ci workflow](https://github.com/mre/hyperjson/tree/master/.github/workflows)

**Comment by ManevilleF** [comment]
The actions don't seem to be checked for pull requests

**Comment by nmandery** [comment]
CI should now run again on PRs to the master branch.
