### ISSUE TITLE
Open to inline comments?

### ISSUE THREAD

**Issue by vanyabrucker** [nmandery/h3ron#75]
I have been going trough the h3ron code and added some comments to get a better understanding. 

What are your thoughts on inline code comments? Should I submit a pull request with my additions or do you prefer to keep it simple?

Are there particular style preferences regarding comments?

Vanya :)

**Comment by nmandery** [comment]
Hi!

Inline comments describing what is done are of course welcome. I would just want to avoid to add comments describing more-or-less obvious code parts - these do not help to much and also do not age well in my experience.

So, just go ahead and submit a PR to add comments where you see the need ;)
