### ISSUE TITLE
Build problem due to geo dependency

### ISSUE THREAD

**Issue by mgnolde** [nmandery/h3ron#76]
The latest crate version of `h3ron` is `v0.17.0`, which uses `v^0.23` of the `geo` crate (https://crates.io/crates/h3ron/0.17.0/dependencies). However, this version of `geo` seems to be somehow defective  (see https://github.com/rust-lang/rust/issues/110776) and therefore, the build process on my machine fails with:
```
error[E0275]: overflow evaluating the requirement
error: could not compile `geo` (lib) due to previous error
```

When installing `h3ron` pointing to the github source in `Cargo.toml`, the problem vanishes. So it looks like the crate dependencies need to be updated to a higher `geo` version.

**Comment by nmandery** [comment]
The release was originally waiting on #73, but there still has been no upstream release.

I will do some more of the missing upgrades and create a new release as soon as I get. Will probably take a bit of time due to the current busy pre-christmas days.

**Comment by mgnolde** [comment]
Great, thanks!
There's no hurry, the workaround using github does it's job (and pre-christmas days are stressful enough).

**Comment by nmandery** [comment]
v0.18.0 is now on crates.io

**Comment by mgnolde** [comment]
Thanks!
