### ISSUE TITLE
Add documentation for experimental `local_to_ij` and `ij_to_local`

### ISSUE THREAD

**Issue by ManevilleF** [nmandery/h3ron#9]
I've been trying to undestand the results of the methods:
- `h3_to_local_ij`
- `local_ij_to_h3`

and I don't get it.

In the test example you take an Index `i` (0x89283080ddbffff) and get a neighbor `N` through `k_ring(1)` and the result is `CoordIJ { i: 1111, j: 620 }`.
I think it has something to do with the resolution of `i` (9) but I don't understand how to use this result.

I would expect `CoordIJ` between two neighbours to be between `(-1, -1)` and `(1, 1)`.

I can't find documentation on this on **Uber** H3 lib so if you understand this result can you explain it or add documentation on the methods?

**Comment by nmandery** [comment]
There is not really a lot of documentation for the experimental CoordIJ functions sadly. A little bit exists [here](https://h3geo.org/docs/core-library/coordsystems). I played around with these functions a while ago trying to implement a region-growing algorithm, but abandoned it after a while. I just had a quick look, but seems I do not have that anymore - and to be honest - I do not remember to many details of CoordIJ anymore.

I also had that expectation in the beginning that all indices of ring 1 around an origin index are in the range of '(-1..1, -1..1)', but the last bullet point of the link above mentions

> the origin may not be at (0, 0) in the local coordinate space.

So `origin` **seems** to be only used to determinate which local coordinate system to use. I just modified the unittest to this:

```rust
    #[test]
    fn test_local_ij() {
        let index = Index::try_from(0x89283080ddbffff_u64).unwrap();
        let ring = index.k_ring(1);
        assert_ne!(ring.len(), 0);
        let other = ring.iter().find(|i| **i != index).unwrap().clone();

        let coordij1 = h3_to_local_ij(&index, &index).unwrap();
        dbg!(coordij1.i);
        dbg!(coordij1.j);
        let coordij = h3_to_local_ij(&index, &other).unwrap();
        dbg!(coordij.i);
        dbg!(coordij.j);
        let other2 = local_ij_to_h3(&index, &coordij).unwrap();
        assert_eq!(other, other2);
    }
```

Looking at the output, there is exactly the behaviour we both expected with Index `i` having an offset of `-1..1` in both directions. It is just that origin is not at `(0, 0)`:

```
[h3ron/src/experimental.rs:65] coordij1.i = 1110
[h3ron/src/experimental.rs:66] coordij1.j = 619
[h3ron/src/experimental.rs:68] coordij.i = 1111
[h3ron/src/experimental.rs:69] coordij.j = 620
```  

Hope this helps a bit.

**Comment by ManevilleF** [comment]
You are right we can do:
```rust
        let local_ijk = h3_to_local_ij(&index, &index).unwrap();
        let diff_ijk = h3_to_local_ij(&index, &neighbor_index).unwrap();
        let ijk = CoordIJ {
            i: diff_ijk.i - local_ijk.i,
            j: diff_ijk.j - local_ijk.j,
        };
        assert_eq!(ijk, CoordIJ { i: -1, j: -1 });
```
And the other way around
```rust
        let local_ijk = h3_to_local_ij(&neighbor_index, &neighbor_index).unwrap();
        let diff_ijk = h3_to_local_ij(&neighbor_index, &index).unwrap();
        let ijk = CoordIJ {
            i: diff_ijk.i - local_ijk.i,
            j: diff_ijk.j - local_ijk.j,
        };
        assert_eq!(ijk, CoordIJ { i: 1, j: 1 });
```

It would be nice to implement `CoordIJ - CoordIj` to avoid doing the substraction directly

**Comment by nmandery** [comment]
Here is some more documentation on the topic: https://github.com/uber/h3/issues/242
